# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#

# -- Project information -----------------------------------------------------
project = 'રાસ-ગરબા સંગ્રહ'
copyright = '2013-2018, P Adhia'
author = 'P Adhia'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.githubpages',
]

templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------
html_theme = "sphinx_rtd_theme"

def setup(app):
    app.add_stylesheet('css/rtd_override.css')

# html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_theme_options = {
    'collapse_navigation': False,
    'display_version': False,
}

# -- Options for manual page output ------------------------------------------
html_show_sourcelink = False
html_show_sphinx = False
html_show_copyright = True
html_static_path = ['_static']
html_logo = "_static/દાંડિયા.jpg"

# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    'papersize': 'letterpaper',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'raas-garba.tex', 'raas-garba Documentation',
     'P Adhia', 'manual'),
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'raas-garba', 'raas-garba Documentation',
     author, 'raas-garba', 'One line description of project.',
     'Miscellaneous'),
]

# -- Extension configuration -------------------------------------------------
