name: pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        external_repository: raas-garba/raas-garba.github.io
        publish_branch: master
